
### getting all users
GET http://localhost:3000/user


### User Login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "password": "kim-22",
    "email": "kim@dev.com"
}


### Create User
POST http://localhost:3000/user/create
Content-Type: application/json

{
    "firstName": "Kim",
    "lastName": "Adorna",
    "birthDay": "03-04-1999",
    "password": "kim-22",
    "email": "kim@dev.com"
}


### delete business
DELETE http://localhost:3000/business/delete/637b2b9bb31fb40f23c2cb7c


### Update business
PATCH http://localhost:3000/business/update/637b3d57e6bc8b0b35360c4a
Content-Type: application/json

{
    "barangay": "San Fermin"
}


### create business
POST  http://localhost:3000/business/create
Content-Type: application/json

{
    "name": "NATHANIEL'S NATURE DROPS WATER REFILLING STATION",
    "address": "TAGARAN, CAUAYAN CITY, ISABELA",
    "lat": 16.96502997100683,
    "lng": 121.7780490411296,
    "barangay": "Tagaran",
    "classification": "Medium"
}

### get all businesses
GET http://localhost:3000/business


### getting all favorite items
GET http://localhost:3000/favorite


### get all barangays
GET http://localhost:3000/business/all/brgys


### favorites
POST  http://localhost:3000/favorite/add
Content-Type: application/json

{
    "userId": "637860538e200281d78d3b9d",
    "businessId": "637b28bd5b7e67527f5897b4"
}


### get favorite
GET http://localhost:3000/favorite/637860538e200281d78d3b9d


### delete favorite
DELETE http://localhost:3000/favorite/delete/637ae1abefeaa37a1acf7eba